python sdxl_generation.py \
    --output_dir /share2/huangrenyuan/logs/ground_diffusion \
    --pretrained_model_name_or_path /share2/huangrenyuan/model_zoo/stable-diffusion-xl-base-1.0 \
    --variant fp16 \
    --train_data_dir /share2/huangrenyuan/dataset/imagenet512.zip \
    --train_batch_size 1 \
    --gradient_checkpointing \
    --class_token "<cls>" \
    --mixed_precision no \
    --learning_rate 1e-4 \
    --seed 42 \
    --test_num 1000 \
    --test_rabbit \
    --resolution 512 \
    --attn_map
    --initializer_token object \